export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const CREATE_PRODUCTS_BEGIN = "CREATE_PRODUCTS_BEGIN"
export const CREATE_PRODUCTS_SUCCESS = "CREATE_PRODUCTS_SUCCESS"
export const CREATE_PRODUCTS_FAILURE = "CREATE_PRODUCTS_FAILURE"

export const EDIT_PRODUCTS_BEGIN = "EDIT_PRODUCTS_BEGIN"
export const EDIT_PRODUCTS_SUCCESS = "EDIT_PRODUCTS_SUCCESS"
export const EDIT_PRODUCTS_FAILURE = "EDIT_PRODUCTS_FAILURE"

export const DELETE_PRODUCTS_BEGIN = "DELETE_PRODUCTS_BEGIN"
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS"
export const DELETE_PRODUCTS_FAILURE = "DELETE_PRODUCTS_FAILURE"

